version: "3.9"
services:
    web:
      build: ./dashboard-web
      ports:
        - "3000:80"
    database:
      build: ./dashboard-database
      volumes:
        - dbdata:/var/lib/postgresql/data
      networks:
        - apinet
    api:
      build: ./dashboard-api
      ports:
        - "8080:8080"
      networks:
        - apinet
      # This makes mcmsdb resolve to database service
      links:
        - "database:mcmsdb"
      depends_on: 
        - database
    aggregatorservice:
      build: ./aggregatorservice
      environment:
        FRONTENDHOSTNAME: localhost
        FRONTENDPORT: 3000
        HTTP_PORT: 3002
      # This doesn't actually work unless curl is on the container, but whatever :)
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      ports:
        - "7777:3002"
    supplementalservice:
      build: ./supplementalservice
      ports:
        - "3002:3002"
      environment:
        HOSTNAME: localhost
        PORT: 3002
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]

networks:
    apinet:
volumes:
    dbdata: