apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cert-manager-app
  namespace: default
spec:
  serviceAccountName: default-cluster-sa
  fetch:
  - git:
      url: https://github.com/pronibs/capstone.git
      ref: origin/develop
      subPath: infrastructure/cert-manager
  - http:
      url: https://github.com/jetstack/cert-manager/releases/download/v1.6.0/cert-manager.yaml

  template:
  - helmTemplate:
      name: cert-manager
      path: 1/cert-manager/
      namespace: cert-manager
      valuesFrom:
      - path: 0/values.yaml

  deploy:
  - kapp: {}