controller:
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to Andrew's CI\CD server.  This Jenkins is configured and managed 'as code'. Top kek.
        jobs:
          - script: >
              pipelineJob('capstone') {
                properties {
                  githubProjectUrl('https://github.com/pronibs/capstone')
                }
                configure { it / 'triggers' / 'com.cloudbees.jenkins.GitHubPushTrigger' / 'spec' }
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/pronibs/capstone.git')
                        }
                        branches('*/main', '*/develop')
                        extensions {
                          submoduleOptions {
                            disable(false)
                            recursive(true)
                          }
                        }
                      }
                    }
                    lightweight()
                  }
                }
              }
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - string:
                      scope: GLOBAL
                      id: "pronibs-pat"
                      secret: "${pronibs-pat-password}"
                      description: "ProNibs Github PAT pulled from K8s"
        unclassified:
          githubpluginconfig:
            configs:
              - name: "Github"
                apiUrl: "https://api.github.com"
                credentialsId: "[pronibs-pat]"
                manageHooks: true
        

      
  additionalPlugins:
    - github:1.34.1
    - job-dsl:1.78.1
  additionalExistingSecrets:
    - name: pronibs-pat
      keyName: password
# agent:
#  additionalAgents:
#     podName: "container-build-agent"    
#     customJenkinsLabels: "docker"
#     image: gcr.io/kaniko-project/executor
#     command: "/busybox/cat"


