nexus:
  docker:
    enabled: true
ingress:
  enabled: true
  # Can't just use "", it'll just place it as raw string lolz
  #hostRepo: '"*."'
  hostRepo: localhost
  #hostPath: /
  #tls:
    #secretName: false
  