nexus:
  docker:
    enabled: true
    registries:
      - host: "localhost"
        port: 5000
        secretName: registry-secret
ingress:
  enabled: true
  # Can't just use "", it'll just place it as raw string lolz
  #hostRepo: '"*."'
  #kubernetes.io/ingress.class: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  hostRepo: nexus.local
  hostPath: /nexus/
  tls:
    - secretName: nexus-local-tls
      hosts:
        - "localhost"
  