apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: harbor
  namespace: harbor
spec:
  # Pick up my-harbor-core's pod specifically
  selector:
    app: harbor
    component: core
  ports:
  - name: http-web
    port: 8443
    protocol: TCP
    targetPort: 8080
