#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata": {"name": "nexus-repository-manager-docker-5000"}}), expects="0+"
---
#@overlay/match-child-defaults missing_ok=True
metadata:
  annotations:
    #@overlay/remove
    nginx.ingress.kubernetes.io/rewrite-target:
  